name: First Workflow

'on':
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  first-job:
    runs-on: ubuntu-24.04

    steps:
    - name: Mostrar información
      run: |
        echo "Hola a Mundo"
        echo "Repositorio Owner: ${{ github.repository_owner }}"
        echo "Repositorio Owner Id: ${{ github.repository_owner_id }}"
        echo "Repositorio ID: ${{ github.repository_id }}"
